services:
  whisper:
    network_mode: 'host'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8765:8765'
    environment:
      - MODEL=tiny
      - VAD_MODE=2
    volumes:
      - ./recordings:/app/recordings
